version: "3"
services:

  grafana:
    image: grafana/grafana:6.2.4
    environment:
      - GF_PATHS_PLUGINS=/fs/grafana/plugins
    volumes:
      - ./grafana/plugins:/fs/grafana/plugins
    ports:
      - 3000:3000
    user: "104"


volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge